"""Add Events, Labels, and Recurrence models

Revision ID: 9d36cba33533
Revises: 
Create Date: 2026-02-16 11:20:47.037630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d36cba33533'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurrence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DOW', 'DOM', 'DAY', 'WEEK', 'MONTH', 'YEAR', name='recurrencetype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('recurrence_id', sa.Integer(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['recurrence_id'], ['recurrence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurrence_to_dom',
    sa.Column('day_of_week', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN', name='dayofmonth'), nullable=False),
    sa.Column('recurrence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recurrence_id'], ['recurrence.id'], ),
    sa.PrimaryKeyConstraint('day_of_week', 'recurrence_id')
    )
    op.create_table('recurrence_to_dow',
    sa.Column('day_of_week', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN', name='dayofweek'), nullable=False),
    sa.Column('recurrence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recurrence_id'], ['recurrence.id'], ),
    sa.PrimaryKeyConstraint('day_of_week', 'recurrence_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurrence_to_dow')
    op.drop_table('recurrence_to_dom')
    op.drop_table('event')
    op.drop_table('recurrence')
    op.drop_table('label')
    # ### end Alembic commands ###
