"""
This type stub file was generated by pyright.
"""

class MissingInputError(Exception):
    """Called if a user doesn't suppy a mandatory input"""
    def __init__(self, expected_name, expected_type) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class InvalidParameterTypeError(Exception):
    """Called if the developer supplies a non-standard parameter type"""
    def __init__(self, invalid_type) -> None:
        ...
    


class ValidationError(Exception):
    """Called if parameter validation fails"""
    def __init__(self, error_string, input_name, input_type) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class ConfigurationError(Exception):
    """Called if app configuration is invalid"""
    def __init__(self, message) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


