"""
This type stub file was generated by pyright.
"""

docs_blueprint = ...
def get_route_docs(include_raw_type=...): # -> list[Any]:
    """
    Generate documentation for all Flask routes that use the ValidateParameters decorator.
    Returns a list of dictionaries, each containing documentation for a particular route.
    """
    ...

def get_function_docs(func, include_raw_type=...): # -> dict[str, Any] | None:
    """
    Get documentation for a specific function that uses the ValidateParameters decorator.
    Returns a dictionary containing documentation details, or None if the decorator is not used.
    """
    ...

def format_docstring(docstring): # -> None:
    """
    Format a function's docstring for HTML display.
    """
    ...

def extract_argument_details(fdocs, include_raw_type=...): # -> dict[Any, Any]:
    """
    Extract details about a function's arguments, including type hints and ValidateParameters details.
    Optionally, raw type information can be included - the default behavior is to omit this, to allow for JSON serialization.
    """
    ...

def recursively_resolve_type_hint(type_to_resolve): # -> str:
    ...

def get_arg_type_hint(fdocs, arg_name): # -> tuple[str | Any, Any]:
    """
    Extract the type hint for a specific argument.
    """
    ...

def get_arg_location(fdocs, idx): # -> str:
    """
    Determine where in the request the argument comes from (e.g., Route, Json, Query).
    """
    ...

def get_arg_location_details(fdocs, idx): # -> dict[Any, Any]:
    """
    Extract additional details about the location of an argument in the request.
    """
    ...

@docs_blueprint.app_template_filter()
def http_badge_bg(http_method): # -> str:
    """
    Provide a color badge for various HTTP methods.
    """
    ...

@docs_blueprint.route("/")
def docs_html(): # -> str:
    """
    Render the documentation as an HTML page.
    """
    ...

@docs_blueprint.route("/json")
def docs_json(): # -> Response:
    """
    Provide the documentation as a JSON response.
    """
    ...

def fpv_error(message): # -> Response:
    ...

def parameter_required(param): # -> bool:
    ...

def generate_json_schema_helper(param: dict, param_type: str, raw_type): # -> dict[Any, Any]:
    ...

def generate_json_schema_for_parameter(param): # -> dict[Any, Any]:
    ...

def generate_json_schema_for_parameters(params): # -> dict[str, Any]:
    ...

def generate_openapi_paths_object(): # -> dict[Any, Any]:
    ...

@docs_blueprint.route("/openapi")
def docs_openapi(): # -> Response:
    """
    Provide the documentation in OpenAPI format
    """
    ...

