"""
This type stub file was generated by pyright.
"""
from typing import Callable, TypeVar

F = TypeVar("F", bound=Callable[..., object])

fn_list = ...
list_type_hints = ...
class ValidateParameters:
    @classmethod
    def get_fn_list(cls): # -> dict[Any, Any]:
        ...

    def __init__(self, error_handler=..., route_deprecated=..., openapi_responses=...) -> None:
        ...

    def __call__(self, f: F) -> F:
        """
        Parent flow for validating each required parameter
        """
        ...

    def validate(self, expected_input, all_request_inputs): # -> list[list[Any]] | list[Any] | None:
        """
        Validate that a given expected input exists in the requested input collection
        """
        ...


