"""
This type stub file was generated by pyright.
"""

from werkzeug.datastructures import FileStorage
from .parameter import Parameter

"""
    Files passed in a POST.
    - Would originally be in Flask's request.file
    - Value will be a FileStorage object
"""
class File(Parameter):
    name = ...
    def __init__(self, default=..., content_types=..., min_length=..., max_length=...) -> None:
        ...
    
    def validate(self, value: FileStorage): # -> Literal[True]:
        ...
    


