"""
This type stub file was generated by pyright.
"""

from .query import Query

"""
    Values sent in a POST Form request
    - Typical data from an HTML form (non-json)
"""
class Form(Query):
    name = ...
    def __init__(self, default=..., **kwargs) -> None:
        ...
    


