"""
This type stub file was generated by pyright.
"""

from typing import Type
from flask_parameter_validation.parameter_types.parameter import Parameter

class MultiSource(Parameter):
    name = ...
    def __init__(self, *sources: list[Type[Parameter]], **kwargs) -> None:
        ...
    


