"""
This type stub file was generated by pyright.
"""

"""
    Base Parameter class.
    Should only be used as child class for other params.
"""
class Parameter:
    def __init__(self, default=..., min_str_length=..., max_str_length=..., min_list_length=..., max_list_length=..., min_int=..., max_int=..., whitelist=..., blacklist=..., pattern=..., func=..., datetime_format=..., comment=..., alias=..., json_schema=..., blank_none=..., list_disable_query_csv=...) -> None:
        ...
    
    def func_helper(self, v): # -> None:
        ...
    
    def validate(self, value): # -> Literal[True]:
        ...
    
    def convert(self, value, allowed_types, current_error=...):
        """Some parameter types require manual type conversion (see Query)"""
        ...
    


