"""
This type stub file was generated by pyright.
"""

from typing import Any

"""
    Query Parameters
    - i.e. sent in GET requests, /?username=myname
"""
def Query(default: Any =..., **kwargs: Any) -> Any: ...

