"""
This type stub file was generated by pyright.
"""

from typing import Any

"""
    Route Parameters
    - Sent as part of a path, i.e. /user/<int:id>
"""
def Route(default=Any, **kwargs: Any) -> Any: ...

